version: '3'

services:
  app:
    build: .
    ports:
      - 9999:9999
    environment:
      REDIS_URI: "tcp://redis:6379"
      WEB_APP_PORT: "9999"
  redis:
    image: "redis"
    ports:
      - 6379:6379
